package:
  name: hashlib
  version: 1.0.0 # Nonsense
  tag:
    - always
  top-level:
    - _hashlib
source:
  path: src
build:
  type: cpython_module
  script: |
    wget ${PYTHON_ARCHIVE_URL} -O Python-${PYVERSION}.tgz
    tar -xf Python-${PYVERSION}.tgz
    cd Python-${PYVERSION}

    emcc $STDLIB_MODULE_CFLAGS -c Modules/_hashopenssl.c -o _hashlib.o \
    -I/Users/tom/dev/github.com/tom-dudley/pyodide/packages/openssl/build/openssl-1.1.1w/include -DOPENSSL_THREADS

    emcc _hashlib.o -o _hashlib.so $SIDE_MODULE_LDFLAGS \
      -L/Users/tom/dev/github.com/tom-dudley/pyodide/packages/openssl/dist -DOPENSSL_THREADS

    cp _hashlib.so ${PKG_BUILD_DIR}/_hashlib.so

requirements:
  run:
    - openssl
  host:
    - openssl
about:
  license: PSF
